//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRM_TBL_USER_MASTER
    {
        public int USER_CODE { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_FNAME { get; set; }
        public System.DateTime EMP_DOB { get; set; }
        public string EMP_GENDER { get; set; }
        public string EMP_CONADDRESS { get; set; }
        public System.DateTime EMP_DOJ { get; set; }
        public string EMP_DESIGNATION { get; set; }
        public string EMP_PROFILE { get; set; }
        public string EMP_QUALIFICATION { get; set; }
        public string EMP_JOBSTATUS { get; set; }
        public string LOGIN_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string HOST_NAME { get; set; }
        public Nullable<decimal> ROLE_CODE { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<decimal> CREATED_USER_CODE { get; set; }
        public string DELETED { get; set; }
        public string SUBDIVISION_CODE { get; set; }
        public string SECTION_CODE { get; set; }
        public string CONSUMER_GRP { get; set; }
        public Nullable<decimal> SUPERVISORCODE { get; set; }
        public string EMP_TELNO { get; set; }
        public string EMP_MOBNO { get; set; }
        public string EMP_FAX { get; set; }
        public string EMP_EMAIL { get; set; }
        public string HIERARCHY_NAME { get; set; }
        public Nullable<decimal> HIERARCHY_CODE { get; set; }
        public Nullable<decimal> DIVISION_CODE { get; set; }
        public Nullable<decimal> PAY_COUNTER_NO { get; set; }
        public int EMP_DEPT { get; set; }
        public string LOGIN_REQUIRED { get; set; }
        public string FS_EXECUTIVE { get; set; }
        public string EMP_HR_CODE { get; set; }
        public string EMP_MNAME { get; set; }
        public string EMP_LNAME { get; set; }
        public string EMP_FHNAME { get; set; }
        public Nullable<int> MANAGER_CODE { get; set; }
        public string EMP_DEPT_SUBCATG { get; set; }
        public string LOGGED_IN { get; set; }
        public string MARITALSTATUS { get; set; }
        public string JOBCATEGORY { get; set; }
    }
}
