//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DischargeSummary
    {
        public int ID { get; set; }
        public string PRNO { get; set; }
        public Nullable<decimal> A_Weight { get; set; }
        public Nullable<decimal> A_Height { get; set; }
        public Nullable<decimal> A_BMI { get; set; }
        public Nullable<decimal> A_FatMass { get; set; }
        public Nullable<decimal> A_FatMassIndex { get; set; }
        public Nullable<decimal> A_FatFreeMass { get; set; }
        public Nullable<decimal> A_FatFreeMassIndex { get; set; }
        public Nullable<decimal> A_TotalBodyWater { get; set; }
        public byte[] A_Report { get; set; }
        public Nullable<decimal> D_Weight { get; set; }
        public Nullable<decimal> D_Height { get; set; }
        public Nullable<decimal> D_BMI { get; set; }
        public Nullable<decimal> D_FatMass { get; set; }
        public Nullable<decimal> D_FatMassIndex { get; set; }
        public Nullable<decimal> D_FatFreeMass { get; set; }
        public Nullable<decimal> D_FatFreeMassIndex { get; set; }
        public Nullable<decimal> D_TotalBodyWater { get; set; }
        public byte[] D_Report { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
