//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feast_Details
    {
        public int ID { get; set; }
        public string PRNO { get; set; }
        public string Feast_Name { get; set; }
        public Nullable<System.TimeSpan> Feast_Time { get; set; }
        public Nullable<System.DateTime> Created_dt { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Modified_dt { get; set; }
        public string Modified_by { get; set; }
        public string Guest_name { get; set; }
    }
}
