//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int ing_id { get; set; }
        public string INGREDIENT_NAME { get; set; }
        public string cost { get; set; }
        public string CALORIES_KCAL { get; set; }
        public string PROTEIN_GM { get; set; }
        public string FATS_GM { get; set; }
        public string FIBRE_GM { get; set; }
        public string CARBO_HYDRATES_GM { get; set; }
        public string CALCIUM_MG { get; set; }
        public string PHOSPOROUS_MG { get; set; }
        public string IRON_MG { get; set; }
        public string CAROTENE_YG { get; set; }
        public string THAIMINE_MG { get; set; }
        public string RIBOFLAVIN_MG { get; set; }
        public string NAICIN_MG { get; set; }
        public string VITAMIN_B6_MG { get; set; }
        public string FOLIC_ACID_YG { get; set; }
        public string VITAMIN_C_MG { get; set; }
        public string VITAMIN_E_MG { get; set; }
        public string MAGNESIUM_MG { get; set; }
        public string SODIUM_MG { get; set; }
        public string POTASSIUM_MG { get; set; }
        public string COPPER_MG { get; set; }
        public string MANGENESE_MG { get; set; }
        public string ZINC_MG { get; set; }
        public string SULPHOR_MG { get; set; }
        public string CHOLINE_MG { get; set; }
        public string MOISTURE_GM { get; set; }
        public string MINERAL_GM { get; set; }
        public string MOLYBDENUM_MG { get; set; }
        public string CHROMIUM_MG { get; set; }
        public string CHOLORINE_MG { get; set; }
        public string values_from { get; set; }
    }
}
