//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveManagement
    {
        public int LeaveId { get; set; }
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Designation { get; set; }
        public string Type_of_Leave { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string No_of_Days { get; set; }
        public string Contact_Number { get; set; }
        public string Purpose_of_Leave { get; set; }
        public string Leaves_Entitled { get; set; }
        public string Leaves_Availed { get; set; }
        public string Leaves_Available { get; set; }
        public string Status_of_Leave { get; set; }
        public string Signed_by_HR { get; set; }
        public string Recommended_By { get; set; }
        public string Approved_By { get; set; }
        public Nullable<System.DateTime> Date_of_Apply { get; set; }
        public Nullable<System.DateTime> Created_dt { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Modified_dt { get; set; }
        public string Modified_by { get; set; }
    }
}
