//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_MEMBERSHIPDETAILS_DETAILS
    {
        public int ID { get; set; }
        public string PRNO { get; set; }
        public int Doc_Num { get; set; }
        public string Mem_ID { get; set; }
        public Nullable<System.DateTime> Visit_Start { get; set; }
        public Nullable<System.DateTime> Visit_End { get; set; }
        public Nullable<int> Discount_ { get; set; }
        public Nullable<decimal> Disc_Amt { get; set; }
    }
}
