//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_PACKAGE_MASTER
    {
        public int Id { get; set; }
        public string Package_Code { get; set; }
        public string PackageType { get; set; }
        public string PackageName { get; set; }
        public string Room_View { get; set; }
        public string Room_Type { get; set; }
        public decimal SO_Pkg_Amt { get; set; }
        public decimal DO_Pkg_Amt { get; set; }
        public decimal SO_Calc_Amt { get; set; }
        public decimal DO_Calc_Amt { get; set; }
        public string Package_Description { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public System.DateTime EffetedFrom { get; set; }
        public System.DateTime EffetedTo { get; set; }
        public Nullable<decimal> SO_Tax_Amt { get; set; }
        public string OfferValid { get; set; }
        public Nullable<decimal> DO_Tax_Amt { get; set; }
        public int Displayorder { get; set; }
        public string Active { get; set; }
    }
}
