//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_CAMPAIGN_MASTER
    {
        public int ID { get; set; }
        public string Camp_Code { get; set; }
        public string Camp_Name { get; set; }
        public int Discount_ { get; set; }
        public string MemberShipReq { get; set; }
        public string Active { get; set; }
    }
}
