//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_VITAL_MASTER
    {
        public int id { get; set; }
        public string vital_name { get; set; }
        public string vital_normal_range { get; set; }
        public string vital_unit { get; set; }
        public string vital_plus_tolerance { get; set; }
        public string vital_minus_tolerance { get; set; }
    }
}
