//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_NUMBERING_SERIES
    {
        public decimal REQUEST_CODE { get; set; }
        public string REQUEST_SHORT_FORM { get; set; }
        public string PREVIOUS_NUMBER { get; set; }
        public string CURRENT_NUMBER { get; set; }
        public string Description { get; set; }
    }
}
