//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_GUEST_ROOM_TRANSACTION
    {
        public string Room_No { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string PRNO { get; set; }
        public string Status { get; set; }
        public int Id { get; set; }
        public string CheckedOut { get; set; }
        public string HKClearance { get; set; }
    }
}
