//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_Guest_Group_Master
    {
        public int ID { get; set; }
        public string Group_Code { get; set; }
        public string Group_Name { get; set; }
        public decimal Discount_Percent { get; set; }
        public string Remarks { get; set; }
    }
}
