//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_PAYMENT_MODE_MASTER
    {
        public int PAYMENT_MODE_CODE { get; set; }
        public string PAYMENT_MODE { get; set; }
        public string PAYMENT_MODE_MANUAL_CODE { get; set; }
    }
}
