//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_Treatment_Master
    {
        public int Id { get; set; }
        public string Treatment_Type { get; set; }
        public string Treatment_Name { get; set; }
        public Nullable<int> Duration_Min { get; set; }
        public Nullable<decimal> UnitCharge { get; set; }
        public string TreatCode { get; set; }
        public string Category { get; set; }
        public string Active { get; set; }
    }
}
