//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_MEMBERSHIPDETAILS_HEADER
    {
        public int ID { get; set; }
        public int Doc_No { get; set; }
        public string UHID { get; set; }
        public string Mem_Id { get; set; }
        public string Mem_Code { get; set; }
        public System.DateTime Mem_StartDate { get; set; }
        public System.DateTime Mem_EndDate { get; set; }
        public string ReferralFrom { get; set; }
        public string Camp_Code { get; set; }
        public decimal Price_AfterDisc { get; set; }
        public string Mem_Payment_Status { get; set; }
        public string ReferralOthers { get; set; }
        public string ReferralUHID { get; set; }
        public string CallingStatus { get; set; }
        public string CallingRemarks { get; set; }
        public string RenewalCallingStatus { get; set; }
        public string RenewalCallingRemarks { get; set; }
        public string RenewalStatus { get; set; }
    }
}
