//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_MEMBERSHIPDETAILS_MASTER
    {
        public int ID { get; set; }
        public string Mem_Code { get; set; }
        public string Mem_Type { get; set; }
        public string Mem_Name { get; set; }
        public decimal Mem_Price { get; set; }
        public int Mem_Duration { get; set; }
        public int Mem_Visits { get; set; }
        public string Mem_Desc { get; set; }
        public string Active { get; set; }
        public string Mem_VisitType { get; set; }
    }
}
