//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nc_tbl_bill_type_master
    {
        public int Bill_TYPE_CODE { get; set; }
        public string BILL_TYPE { get; set; }
        public string BILL_TYPE_MANUAL_CODE { get; set; }
        public string Billing_FLAG { get; set; }
        public string Fixed { get; set; }
        public Nullable<decimal> Fixed_Amount { get; set; }
    }
}
