//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_ROOM_MASTER
    {
        public string Room_No { get; set; }
        public string Room_View { get; set; }
        public string Room_Type { get; set; }
        public string Floor { get; set; }
        public string Specific_To { get; set; }
        public decimal SO_Tariff { get; set; }
        public decimal DO_Tariff { get; set; }
        public string Room_Condition { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> Effect_From_Date { get; set; }
        public Nullable<System.DateTime> Closing_Date { get; set; }
    }
}
