//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_HEALTH_DETAILS
    {
        public int Id { get; set; }
        public string PRNO { get; set; }
        public int HLCode { get; set; }
        public string HLFlag { get; set; }
        public string HLDesc { get; set; }
    }
}
