//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_ROOM_Status
    {
        public int ID { get; set; }
        public string PRNO { get; set; }
        public Nullable<int> Room_No { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date_From { get; set; }
        public Nullable<System.DateTime> Date_To { get; set; }
        public string Guest_Name { get; set; }
        public string Gender { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_dt { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_dt { get; set; }
    }
}
