//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_TBL_PERSONAL_DETAILS
    {
        public int Id { get; set; }
        public string UHID { get; set; }
        public string PRNO { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherHusbandName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string FlatNo { get; set; }
        public string Building { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string Nationality { get; set; }
        public string Country { get; set; }
        public System.DateTime DOB { get; set; }
        public decimal Age { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Occupation { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public string EmergencyContactNo { get; set; }
        public string BP { get; set; }
        public decimal PulseRate { get; set; }
        public string ReferralFrom { get; set; }
        public string ReferralPRNO { get; set; }
        public string AdmissionStatus { get; set; }
        public string User_Type { get; set; }
        public string CheckinProcess { get; set; }
        public Nullable<int> AssignedDoctor { get; set; }
        public string ForwardTo { get; set; }
        public Nullable<System.DateTime> ForwardDate { get; set; }
        public string CheckoutProcess { get; set; }
        public string DischargeType { get; set; }
        public string ReferralOthers { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public string ForwardYoga { get; set; }
        public string GuestPriority { get; set; }
        public string PStatus { get; set; }
        public Nullable<int> AssignedGRO { get; set; }
        public string AliasName { get; set; }
    }
}
