//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pema_dbEntities : DbContext
    {
        public pema_dbEntities()
            : base("name=pema_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nc_tbl_bill_type_master> nc_tbl_bill_type_master { get; set; }
        public virtual DbSet<NC_TBL_Billing_Trans> NC_TBL_Billing_Trans { get; set; }
        public virtual DbSet<NC_TBL_BOOKED_DATES> NC_TBL_BOOKED_DATES { get; set; }
        public virtual DbSet<NC_TBL_CAMPAIGN_MASTER> NC_TBL_CAMPAIGN_MASTER { get; set; }
        public virtual DbSet<NC_TBL_COUNTRY_MASTER> NC_TBL_COUNTRY_MASTER { get; set; }
        public virtual DbSet<NC_TBL_Gateway_Payment_Details> NC_TBL_Gateway_Payment_Details { get; set; }
        public virtual DbSet<NC_TBL_GATEWAYPAYMENT_MODE_MASTER> NC_TBL_GATEWAYPAYMENT_MODE_MASTER { get; set; }
        public virtual DbSet<NC_TBL_Guest_Group_Master> NC_TBL_Guest_Group_Master { get; set; }
        public virtual DbSet<NC_TBL_GUEST_ROOM_TRANSACTION> NC_TBL_GUEST_ROOM_TRANSACTION { get; set; }
        public virtual DbSet<NC_TBL_HABIT_DETAILS> NC_TBL_HABIT_DETAILS { get; set; }
        public virtual DbSet<NC_TBL_HBQuest_master> NC_TBL_HBQuest_master { get; set; }
        public virtual DbSet<NC_TBL_HEALTH_DETAILS> NC_TBL_HEALTH_DETAILS { get; set; }
        public virtual DbSet<NC_TBL_HLQuest_master> NC_TBL_HLQuest_master { get; set; }
        public virtual DbSet<NC_TBL_MEMBERSHIPDETAILS_DETAILS> NC_TBL_MEMBERSHIPDETAILS_DETAILS { get; set; }
        public virtual DbSet<NC_TBL_MEMBERSHIPDETAILS_HEADER> NC_TBL_MEMBERSHIPDETAILS_HEADER { get; set; }
        public virtual DbSet<NC_TBL_MEMBERSHIPDETAILS_MASTER> NC_TBL_MEMBERSHIPDETAILS_MASTER { get; set; }
        public virtual DbSet<NC_TBL_NATIONALITY_MASTER> NC_TBL_NATIONALITY_MASTER { get; set; }
        public virtual DbSet<NC_TBL_NUMBERING_SERIES> NC_TBL_NUMBERING_SERIES { get; set; }
        public virtual DbSet<NC_TBL_PACKAGE_MASTER> NC_TBL_PACKAGE_MASTER { get; set; }
        public virtual DbSet<NC_TBL_PAYMENT_TRANS> NC_TBL_PAYMENT_TRANS { get; set; }
        public virtual DbSet<NC_TBL_PAYMENT_TYPE_MASTER> NC_TBL_PAYMENT_TYPE_MASTER { get; set; }
        public virtual DbSet<NC_TBL_PERSONAL_DETAILS> NC_TBL_PERSONAL_DETAILS { get; set; }
        public virtual DbSet<NC_TBL_ROOM_MASTER> NC_TBL_ROOM_MASTER { get; set; }
        public virtual DbSet<NC_TBL_Treatment_Master> NC_TBL_Treatment_Master { get; set; }
        public virtual DbSet<NC_TBL_VITAL_MASTER> NC_TBL_VITAL_MASTER { get; set; }
        public virtual DbSet<WS_Tbl_Registration> WS_Tbl_Registration { get; set; }
    
        public virtual int gen_unique_no(string rEQSHORTFORM, ObjectParameter uniqueno)
        {
            var rEQSHORTFORMParameter = rEQSHORTFORM != null ?
                new ObjectParameter("REQSHORTFORM", rEQSHORTFORM) :
                new ObjectParameter("REQSHORTFORM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("gen_unique_no", rEQSHORTFORMParameter, uniqueno);
        }
    
        public virtual int Guest_PR_Identification(string pRNO, ObjectParameter prtype, ObjectParameter oppPRNO, ObjectParameter oppName)
        {
            var pRNOParameter = pRNO != null ?
                new ObjectParameter("PRNO", pRNO) :
                new ObjectParameter("PRNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Guest_PR_Identification", pRNOParameter, prtype, oppPRNO, oppName);
        }
    }
}
