//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public int id { get; set; }
        public Nullable<int> recipe_name { get; set; }
        public Nullable<int> ingre { get; set; }
        public string qty { get; set; }
        public string cal { get; set; }
        public string raw_weight { get; set; }
        public string sideheadline { get; set; }
    }
}
