//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MINUTES_OF_MEETING
    {
        public int SlNo { get; set; }
        public Nullable<int> Dept_Code { get; set; }
        public string Key_Point { get; set; }
        public string Description { get; set; }
        public string Responsibility { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Target_Date { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> MOM_Assigned_Date { get; set; }
    }
}
