//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CheckOut_File
    {
        public int ID { get; set; }
        public string PRNO { get; set; }
        public byte[] Bill_File { get; set; }
        public byte[] Discharge_Summery { get; set; }
        public string Bill { get; set; }
        public string Discharge { get; set; }
        public string CheckOut { get; set; }
    }
}
