//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DateofBirths
    {
        public int Id { get; set; }
        public string Emp_name { get; set; }
        public string Emp_designation { get; set; }
        public string Ecno { get; set; }
        public string Dept { get; set; }
        public Nullable<System.DateTime> DateofBirthDate { get; set; }
    }
}
