//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentAvailedOld
    {
        public int ID { get; set; }
        public string PRNO { get; set; }
        public Nullable<int> HealerID { get; set; }
        public Nullable<int> TreatmentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.TimeSpan> SchdeuleTime { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string GuestName { get; set; }
    }
}
