//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentFeedBack
    {
        public int ID { get; set; }
        public int TreatmentAvailedID { get; set; }
        public string Rating { get; set; }
        public string FeedBack { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_dt { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_dt { get; set; }
    
        public virtual TreatmentAvailed TreatmentAvailed { get; set; }
    }
}
