//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_Tbl_Registration
    {
        public string user_id { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public string father_husband_name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string mobile_no { get; set; }
        public System.DateTime Registered_Date { get; set; }
        public string UHID { get; set; }
        public string LOGGED_IN { get; set; }
        public string Active { get; set; }
    }
}
